### ISSUE TITLE
Container does not start - java errors

### ISSUE THREAD

**Issue by RealGandy** [packetworks/docker-nxfilter#21]
New user. 

docker on debian, using DockStarter (beginners easy way into docker) and added following into the docker-compose. override.yml file to run nxfilter container, 

```
   nxfilter:
    container_name: nxfilter
    image: packetworks/nxfilter-base:latest
    tty: true
    volumes:
      - ${DOCKERCONFDIR}/nxfilter/nxfilter-conf:/nxfilter/conf
      - ${DOCKERCONFDIR}/nxfilter/nxfilter-log:/nxfilter/log
      - ${DOCKERCONFDIR}/nxfilter/nxfilter-db:/nxfilter/db
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      - 53:53/udp
      - 19002-19004:19002-19004
    networks:
      composemacvlan:
        ipv4_address: 192.168.2.242 
```     

and get following errors in logs:

```
Exception in thread "main" java.lang.NullPointerException
	at nxd.Main.<init>(Unknown Source)
	at nxd.Main.main(Unknown Source)
Exception in thread "Thread-0" java.lang.NullPointerException
	at nxd.o.run(Unknown Source)
```

A previous [issue](https://github.com/packetworks/docker-nxfilter/issues/14) suggest 'prepopulating' or copying db files. As a new nxfilter user, I'm not sure what this means, so any pointers gratefully received.

Thanks
